language: java
addons:
  apt:
    packages:
    - jython
before_install:
- mkdir ~/.gradle
- echo jythonInterpreter=jython >> ~/.gradle/gradle.properties
script: gradle check -PjythonInterpreter=jython
